## **Deep Learning Framework**
**❓퀴즈**     
다음 중 딥러닝 Framework가 아닌 것은?
1. MXNet
2. Caffe
3. Keras
4. Tensorflow
5. **Pandas**

**🖊 정답:** 5번    
Pandas는 데이터 분석과 처리를 위한 Python 라이브러리
<br><br><br>

**❓퀴즈**
#### **Define by Run**
데이터 흘려보내기와 계산 그래프 구축이 동시에 이루어짐
- PyTorch, Tensorflow(2.0 이상)
- 순방향 계산에 적합, RNN 유용

#### **Define and Run**
계산 그래프 정의 → 컴파일 → 데이터 흘려보내기      
실 데이터가 아닌 기호를 사용해 추상적인 계산 절차를 코딩해야 함.

**🖊 정답:**
- Define and Run 방식은 그래프를 먼저 정의하고 실행 시점에 data를 주입하는 방식이다.
- Define by Run 방식은 실행하면서 그래프를 생성하는 방식이다.
<br><br><br>

**❓퀴즈**   

**🖊 정답:** 딥러닝 프레임워크를 사용하면 미분 연산을 자동으로 처리해주므로, 수작업으로 미분 식을 작성할 필요가 없다.

## **PyTorch basics**
- numpy + AutoGrad

### **Tensor**
- 다차원 배열을 표현하는 PyTorch 클래스
- numpy의 ndarray와 매우 유사
- pytorch의 tensor는 GPU에 올려 사용 가능

### numpy to tensor

In [ ]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)
print("ndim:", n_array.ndim, "shape: ", n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim: 2 shape:  (2, 5)


In [ ]:
import torch
t_array = torch.FloatTensor(n_array)
print(t_array)
print("ndim:", t_array.ndim, "shape: ", t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim: 2 shape:  torch.Size([2, 5])


### Using GPU

In [ ]:
t_array.device # 자동으로 cpu 타입 할당

if torch.cuda.is_available():
    t_array = t_array.to('cuda')
    t_array.cuda.device

### Array to Tensor

In [ ]:
# data to tensor
data = [[3,5],[10,5]]
x_data = torch.tensor(data)

#ndarray to tensor
nd_array_ex = np.array(data)
tensor_array = torch.from_numpy(nd_array_ex)

### **numpy like operations**
- 기본적으로 PyTorch 대부분의 연산에 numpy 연산이 방식이 적용됨

In [ ]:
data = [[3, 5, 20],[10, 5, 50],[1, 5, 10]]
x_data = torch.tensor(data)

x_data[1:]

tensor([[10,  5, 50],
        [ 1,  5, 10]])

In [ ]:
x_data[:2,1:]

tensor([[ 5, 20],
        [ 5, 50]])

**❓퀴즈**

In [ ]:
x_data.flatten()

tensor([ 3,  5, 20, 10,  5, 50,  1,  5, 10])

In [ ]:
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [ ]:
x_data.numpy()

array([[ 3,  5, 20],
       [10,  5, 50],
       [ 1,  5, 10]])

In [ ]:
x_data.shape

torch.Size([3, 3])

In [ ]:
x_data.dtype

torch.int64

### **Tensor handling**
- **view**
    - reshape와 동일하게 tensor의 shape를 변환
- **squeeze**
    - 차원이 1인 차원을 아무거나 삭제(압축)
- **unsqueeze**
    - 차원 개수가 1인 차원을 추가(원하는 dim에 추가 가능)


In [ ]:
tensor_ex = torch.rand(size=(2, 1, 2))
tensor_ex.squeeze()

tensor([[0.6760, 0.0985],
        [0.1611, 0.9635]])

In [ ]:
tensor_ex = torch.rand(size=(2,2))
tensor_ex.unsqueeze(0).shape

torch.Size([1, 2, 2])

In [ ]:
tensor_ex.unsqueeze(1).shape

torch.Size([2, 1, 2])

In [ ]:
tensor_ex.unsqueeze(2).shape

torch.Size([2, 2, 1])


### **view vs reshape**
- **view**
    - 연이은 나열(Contiguity)을 보장.
    - tensor가 메모리에 연속적으로 존재할 때만 사용 가능.
    - Contiguity를 보장하므로, copy없이 더 빠른 연산이 가능하기 때문에 view를 추천
- **reshape**
    - Contiguity를 항상 보장 하지 않음. Contiguity가 깨지면 복사해 새로 할당.
    - 메모리에 연속적으로 tensor가 존재하는 경우 tensor와 메모리를 공유함.

**❓퀴즈**   

**🖊 정답:**
-  view는 오직 contiguous한 tensor에서만 적용할 수 있으며, reshape는 이런 제약이 없다.
- view는 원래 tensor와 메모리를 공유하며, reshape도 가능한 경우에는 원래 tensor와 메모리를 공유한다.


#### **torch.rand 정리**
- **torch.rand(size):**
    - 0과 1 사이의 실수로 난수를 생성해서 tensor 만들기
- **torch.randn(size):**
    - 표준정규분포 X~N(0, 1)로부터 난수를 생성해서 텐서 만들기
- **torch.randint(low, high, size):**
    - low~high사이의 정수로 난수를 생성해서 tensor 만들기
- **torch.randperm(n):**
    - 0~n사이의 정수를 무작위로 섞어 tensor 생성

In [ ]:
tensor_ex = torch.rand(size=(2, 3, 2))
tensor_ex

tensor([[[0.2919, 0.7020],
         [0.0222, 0.2858],
         [0.4513, 0.8274]],

        [[0.9920, 0.2779],
         [0.4236, 0.1790],
         [0.9203, 0.8351]]])

In [ ]:
tensor_ex.view([-1, 6])

tensor([[0.2919, 0.7020, 0.0222, 0.2858, 0.4513, 0.8274],
        [0.9920, 0.2779, 0.4236, 0.1790, 0.9203, 0.8351]])

In [ ]:
tensor_ex.reshape([-1,6])

tensor([[0.2919, 0.7020, 0.0222, 0.2858, 0.4513, 0.8274],
        [0.9920, 0.2779, 0.4236, 0.1790, 0.9203, 0.8351]])

### **Tensor operations**
- tensor의 기본 연산들은 numpy와 동일.
- 행렬곱 연산은 dot이 아닌 **mm** 사용
- mm과 matmul은 **broadcasting 지원** 차이

In [ ]:
# 기본 연산

n1 = np.arange(10).reshape(2,5)
t1 = torch.FloatTensor(n1)

t1 + t1

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.]])

In [ ]:
t1 - t1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
t1 + 10

tensor([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [ ]:
# 행렬곱 연산

n2 = np.arange(10).reshape(5,2)
t2 = torch.FloatTensor(n2)

# mm은 matrix 연산에 사용
t1.mm(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [ ]:
# dot은 scalar, vector 연산에 사용
t1.dot(t2)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [ ]:
t1.matmul(t2)

tensor([[ 60.,  70.],
        [160., 195.]])

In [ ]:
# mm과 matmul의 차이

a = torch.rand(5,2,3)# 5는 배치 사이즈
b = torch.rand(5)
a.mm(b)

RuntimeError: self must be a matrix

In [ ]:
# 아래와 동일한 식
# a[0].mm(torch.unsqueeze(b,1))
# a[1].mm(torch.unsqueeze(b,1))
# a[2].mm(torch.unsqueeze(b,1))
# a[3].mm(torch.unsqueeze(b,1))
# a[4].mm(torch.unsqueeze(b,1))

a = torch.rand(5,2,3)
b = torch.rand(3)
a.matmul(b)

tensor([[0.1749, 0.3173],
        [0.8168, 0.7687],
        [0.6070, 0.5597],
        [0.3983, 0.7248],
        [0.8980, 0.6583]])

### **Tensor operations for ML/DL formula**
- nn.fuctional 모듈을 통해 다양한 수식 변환 지원.

In [ ]:
import torch
import torch.nn.functional as F

tensor = torch.FloatTensor([0.5, 0.7, 0.1])
h_tensor=F.softmax(tensor, dim=0)
h_tensor

tensor([0.3458, 0.4224, 0.2318])

In [ ]:
y = torch.randint(5, (10,5))
y_label = y.argmax(dim=1) #argmax는 주어진 배열에서 가장 높은 값을 가진 인덱스를 반환

torch.nn.functional.one_hot(y_label)

tensor([[0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
        [1, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 1],
        [0, 1, 0, 0]])

### **AutoGrad**
- PyTorch의 핵심은 자동 미분의 지원
    - backward 함수 사용

In [ ]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1,1]) # 크기 지정
Q.backward(gradient=external_grad)

In [ ]:
a.grad

tensor([36., 81.])

In [ ]:
b.grad

tensor([-12.,  -8.])